name: Main Branch CI/CD\

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: target/*.jar

  build_docker:
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app-jar
          path: app/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set proper tag name for Docker image
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          
          BRANCH_NAME_CORRECT=$(echo "$BRANCH_NAME" | sed 's|/|-|g')
          
          echo "TAG_NAME=$BRANCH_NAME_CORRECT" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }} --build-arg JAR_FILE=app/*.jar .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}